### ISSUE TITLE
Crash upon loading server

### ISSUE THREAD

**Issue by TheGamersBrew** [codeHusky/HuskyCrates-Sponge#110]
When ran with Grief Defender, Nucleus and Total Economy the Plug in causes the server to have a crash.

**Comment by Gamefreak2302** [comment]
Can tell they should be able to work together just fine ( there are several players which use those combinations). Would recommend adding the crash report which might be able to look for the issue. the only time huskycrates managed to crash a server was with a missing huskyui or an invalid number at chance for example, so would check that aswell

**Comment by NovaSki11z** [comment]
I use the same ones even have luckperms I do know GD and Husky had issues when using the * as a permission in luckperms take that out and change it to things like nucleus.*. Make sure as well that all your groups inherit default or whatever container you use as default

**Comment by codeHusky** [comment]
No information provided. Feel free to reopen if you can provide logs or something that allows me to know what your talking about

**Comment by TheGamersBrew** [comment]
additional info:
Spongforge
visions:
HuskyCratesrc2.jar (and tried with just HuskyCrates.jar)
GriefDefender-2.0.0
Nucleus2.4.0
TotalEconomy-1.8.1
LuckPerms-sponge-5.3.69

After looking over the messages here i'm assuming that I had needed Huskyui for this to work and that might have caused the server crash. (as the server crash was upon booting it up.
