### ISSUE TITLE
bug with inv sort mod

### ISSUE THREAD

**Issue by MrWhiteFlamesYT-dev** [codeHusky/HuskyCrates-Sponge#112]
Hello huskycrates

This morning I found out by players on my nodded server that they can dupe the items using the inventory sorter mod to obtain all the items being displayed in the gui of a crate.

Is there a way I can fix this without having to remove the mod from server side?

Kind regards
MrWhiteFlamesYT

**Comment by codeHusky** [comment]
Incompatibility with server side inventory manipulation mods is a known thing. There's no way to fix this without you removing the mod unless the mod developer decides to support SpongeAPI.
