### ISSUE TITLE
the file to configure is not showing up

### ISSUE THREAD

**Issue by Stivx77** [codeHusky/HuskyCrates-Sponge#114]
![Screenshot_2023-07-05-16-56-35-473_com android chrome](https://github.com/codeHusky/HuskyCrates-Sponge/assets/138720679/7b14669c-c0d5-4030-a7b4-79cd94b9c1f5)
I'm trying to use your plugin but the file to configure is not showing, could you tell me why?

**Comment by JarnoDK1997** [comment]
Huskycrates also requires husky-ui to work. 
This causes huskycrates to fail, causing the files to not be created 

[Husky ui](https://ore.spongepowered.org/codeHusky/HuskyUI)

**Comment by Gamefreak2302** [comment]
You're missing huskyui, which is a plugin that is required for huskycrates to work. Without it the plugin fails, which ofcourse prevents the creation of the config files 
[Husky-UI](https://ore.spongepowered.org/codeHusky/HuskyUI)

**Comment by Stivx77** [comment]
I installed the husky-ui plugin but when I start it, this appears, do you know how to solve it?
![Screenshot_2023-07-05-20-16-25-059_com android chrome](https://github.com/codeHusky/HuskyCrates-Sponge/assets/138720679/d996b641-f879-44b9-b141-b1ed9c134fda)

**Comment by codeHusky** [comment]
This plugin is built for Sponge, not Bukkit/Spigot/Paper.
