### ISSUE TITLE
how to contact you 

### ISSUE THREAD

**Issue by yololetsplay** [codeHusky/HuskyCrates-Sponge#12]
Hey there ;]

I read an post of you relevent to BadgeUp Achievements.
https://forums.spongepowered.org/t/badgeup-achievements/16525/15

Well, I'm really no fan of web API based things and also "now free"... maybe it costs a lot of money after time.
So, could you program an plugin like this?
I really love an quest like plugin.
It's like leveling up, getting payed for doing quests.

The best would be to run server commands like "/pay [p] 100", so you can use just other plugins and [p] is for the current player.

Maybe you can send me your mail adress or something if you are interested in. I would donate for it ;]

Greetz,
Hannes

**Comment by codeHusky** [comment]
I could make a plugin like this, sure, but you could contact me on discord if you drop your discord tag here.

**Comment by codeHusky** [comment]
I've got a couple of plugins on sponge forums where you could donate as well.
