### ISSUE TITLE
Reload command

### ISSUE THREAD

**Issue by KasperFranz** [codeHusky/HuskyCrates-Sponge#13]
A simple command to reload the config.

for on the fly edit of crates etc :)

**Comment by codeHusky** [comment]
You could also try using /sponge plugins reload in the mean time. I don't plan on a reload command since we respect the reload event.

**Comment by KasperFranz** [comment]
a reload command from inside the plguin would either way be the best option, since i don't want to  reload eg my vote plugin if i have changes to this on the fly

**Comment by codeHusky** [comment]
Meh. Maybe.
