### ISSUE TITLE
Max time and dampening 

### ISSUE THREAD

**Issue by KasperFranz** [codeHusky/HuskyCrates-Sponge#14]
- [x] Ability to set max time (basically "clicks") it takes to stop the spinner
- [x] Ability to adjust the dampening on the spinner so you can fine tune all the magics
- [x] Ability to add slight randomization on the tick count
- [x] Spin times should be reasonable, not taking 20 minutes for long, long crates.

**Comment by codeHusky** [comment]
Please don't duplicate issues, this is already being discussed elsewhere

**Comment by KasperFranz** [comment]
Where?

**Comment by tolly7654** [comment]
I have to agree with kasper on this, where abouts is this issue? If it's elsewhere, then can we be sent a link please?

Thanks,
-tolly765

**Comment by codeHusky** [comment]
Forgot that was on the forums. I'll keep this open here.

**Comment by codeHusky** [comment]
Working on this right now.

**Comment by codeHusky** [comment]
Currently have a hard limit of 45 ticks around the spinner. Will make it customizable later.

**Comment by codeHusky** [comment]
Coming in 0.11.0, now published to the main branch.

**Comment by codeHusky** [comment]
.. Maybe 1.0 even. :)
