### ISSUE TITLE
Some CommunityBuilt-Based Features

### ISSUE THREAD

**Issue by codeHusky** [codeHusky/HuskyCrates-Sponge#22]
- [x] Customizable crate key (per crate / globally)
- [x] reward to ender chest if inv is full (check commbuilt implementation later)
- [ ] customizable UI color
- [x] customizable particle colors
- [x] fix the crappy command format that was really an afterthought
- [x] possible optimization opportunities 

_some of these are still on the roadmap_
@KasperFranz

**Comment by KasperFranz** [comment]
Fixed the "crappy command format" in the pr #25.

**Comment by codeHusky** [comment]
Moved to NFR
