### ISSUE TITLE
v0 to v1 Conversion Issues with unknown forge mods

### ISSUE THREAD

**Issue by VinceOrlando** [codeHusky/HuskyCrates-Sponge#24]
Config is not converting from 0.9 to 0.10.x

**Comment by Jaskirat-Boparai** [comment]
Same issue here.

**Comment by codeHusky** [comment]
please post your config that is not converting because I can't test the problem without that info. @Jaskirat-Boparai

**Comment by codeHusky** [comment]
Also what operating system are you running your server on / sponge version

**Comment by codeHusky** [comment]
Tested, SpongeForge is not the source of the issue. Will be testing on a Linux distribution soon.

**Comment by codeHusky** [comment]
Tested on Ubuntu 16.04 and found no issues when testing on reccomended Forge + SpongeForge, SpongeVanilla.

**Comment by codeHusky** [comment]
Further investigation proves that it's an issue with some mod in some modpacks.

**Comment by codeHusky** [comment]
https://forums.spongepowered.org/t/crazy-huskycrates-config-converter-issues/19009

**Comment by codeHusky** [comment]
Wasn't able to pin down the affected mods with FTB: Beyond. Some weird incompatibilities resulted in removal of some mods which could have been at fault, but testing shows that there may be some discrepancies between my setup workspace and server's setups. So far, I believe that FTB: Beyond and related FTBLib and FTBUtilities aren't necessarily at fault for the *configuration* issues. I'm unable to tell if the issues are a result of another mod that I don't have on my server setup or not. 

If anyone has any more conclusive information (additional installed mods), please post them here to assist in the fixing of these bugs.

**Comment by codeHusky** [comment]
Unfortunately, in better interest of time and actually using my time to improve the plugin rather than trying to fix some odd issue, this conversion problem will be put on hold until I get some additional information on the issue.

**Comment by codeHusky** [comment]
Possibly resolved by a change in time where 1.2.0 loads.

**Comment by codeHusky** [comment]
I'm closing this issue until more reports arise with this issue.
