### ISSUE TITLE
Not receiving a crate or key when I use the command 

### ISSUE THREAD

**Issue by SCOTSChief** [codeHusky/HuskyCrates-Sponge#30]
I am using the example config you made to test if this would work and I just get ?? when i use the command correctly. My OS is Linux as well like I said this is the template one you made so that way I could test the system. 
Just in case you need it vVconfigVv
https://hastebin.com/okuxakogaz.bash

**Comment by codeHusky** [comment]
Could you say how you're typing.the command.

**Comment by codeHusky** [comment]
Are you going /crate chest *id* or /crate *id*

**Comment by SCOTSChief** [comment]
I did the command the way the main page to the get hub said so /crate chest id

**Comment by seshormerow** [comment]
You need to do /crate <id> for the time being, soon the new format will be the way to do it, whenever the next release comes out that's when the new command format is expected.

**Comment by SCOTSChief** [comment]
Ok thank you for the help and keep up the good work it is always good to see devs working hard. But I bet it can be hard so again thank you for all that you have done and for helping me out.
