### ISSUE TITLE
Give all players on server key

### ISSUE THREAD

**Issue by Pokekhan** [codeHusky/HuskyCrates-Sponge#33]
Is there a way to make a command. So it give a key to everyone on the server like ./crate giveall [type] or something on them line.

**Comment by seshormerow** [comment]
Unless there's a way to do it through some sort of naming method, I don't believe so. Potentially a new command, probably for the sake of simplicity we would keep it under the key command and maybe use an asterisk to indicate all players on the map.

**Comment by codeHusky** [comment]
You could try @a but I don't know if that would.work.

**Comment by Pokekhan** [comment]
Nope it give me a error saying that you need to be in game or specify a player for this command to work.

**Comment by Pokekhan** [comment]
Also seshormerow we have a crate plugin on our sponge server and the dev done it for us then. So it must be possible to do.

**Comment by codeHusky** [comment]
It's very possible to do, I'll just need to get time to sit down and do it.

**Comment by Pokekhan** [comment]
Thanks if you get it done 👍

**Comment by codeHusky** [comment]
Moved to NFR
