### ISSUE TITLE
huskycrates.conf

### ISSUE THREAD

**Issue by ziceptor** [codeHusky/HuskyCrates-Sponge#4]
When you remove the crate remains garbage in the config.

**Comment by codeHusky** [comment]
it's not even version 1.0

**Comment by ziceptor** [comment]
Pre-tested.

**Comment by codeHusky** [comment]
What?

**Comment by ziceptor** [comment]
In my spare time I'm testing the open source code and report problems and errors. The fact that the project is not yet complete and has bugs, does not mean that the author knows about them. Especially if working on several projects at the same time.

**Comment by codeHusky** [comment]
Well I'm perfectly fine handling my projects by myself.

**Comment by jon100456** [comment]
can you please make a back port to 1.10 ?

**Comment by codeHusky** [comment]
This isn't the appropriate thread to ask this

**Comment by ziceptor** [comment]
I understand what you claim to me. Let us not mix work and personal. Don't know how clearer to say... English is not my native language.
