### ISSUE TITLE
Particle System Improvements

### ISSUE THREAD

**Issue by codeHusky** [codeHusky/HuskyCrates-Sponge#42]
- [ ] Allow users to change particle math calculations.
- [ ] custom overwatch-esque crate animations (someone else is on this)
    - Would most likely be part of a modified version of instant called `animated`

**Comment by codeHusky** [comment]
@connorhartley

**Comment by randombyte-developer** [comment]
> Allow users to change particle math calculations.

Could be done using `Lua` or `JavaScript`.

**Comment by codeHusky** [comment]
probably js because yes

**Comment by codeHusky** [comment]
Duplicate
