### ISSUE TITLE
Keys still saving to config after DB update

### ISSUE THREAD

**Issue by Jaskirat-Boparai** [codeHusky/HuskyCrates-Sponge#49]
HuskyCrates v1.7.0
HuskyUI v0.2.1 and v0.3.0
**spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar**
Modpacks: Doesn't appear to matter
HuskyCrates config: https://hastebin.com/rupunalace.bash

After every restart, the server fails to load the crate positions from the database, or the world info.
### Working on
- spongeforge-1.11.2-2393-6.1.0-BETA-2471 with a custom modpack, only sharing a few mods
    - shared mods removed from list
    - [Evidence](https://gist.github.com/FiveEYZ/81bf0d23976b7f62ba0fcac9385c0dce)

**Comment by codeHusky** [comment]
According to ShadowKitten on discord, this is 1.7.0 related.

**Comment by codeHusky** [comment]
Additionally: It was reported that this happens only after full server restarts. This might suggest something to do with changing world UUIDs.

**Comment by codeHusky** [comment]
Reported to be working fine by FiveEYZ on Discord on spongeforge-1.11.2-2393-6.1.0-BETA-2471

**Comment by codeHusky** [comment]
Appears to be related to API 5.x. Investigating further.

**Comment by codeHusky** [comment]
![image](https://user-images.githubusercontent.com/6946558/28349112-65c0bd0c-6c06-11e7-9834-73789f574353.png)
![image](https://user-images.githubusercontent.com/6946558/28349117-6b4ddc1e-6c06-11e7-9a2a-997fbe5aac8b.png)

**Comment by codeHusky** [comment]
Appears to not be SpongeForge causing the issue as all of my data loads just fine on both 2281 and 2316.

**Comment by codeHusky** [comment]
**List of possible offending mods**
- ActuallyAdditions
- AppleSkin
- AutoRegLib
- bdlib
- BedBugs
- BetterBuildersWands
- BetterThanBunnies
- BloodMagic
- Botania r1.9
- BrandonsCore
- Ceramics
- Chameleon
- ChestTransporter
- Chisel
- chiselsandbits
- Clipboard
- CodeChickenCore
- CodeChickenLib
- compatlayer
- Controlling
- CookingForBlockheads
- CustomMainMenu
- DarkUtilities
- Decocraft
- Draconic
- DrawersBits
- ElevatorMod[V.1.3.0][MC.1.10.2].jar
- EnderCore
- EnderIO
- EnderStorage
- EngineersWorkshop
- environmentaltech
- etlunar
- extrautils2
- ExtremeReactors
- flatcoloredblocks
- FluxNetworks
- foamfix
- Forgelin
- FTBLib
- FTBUtilities
- Funnels
- GraveStone Mod 1.5.12.jar
- Guide
- HammerCore
- hopperducts
- ImmersiveEngineering
- InGameInfoXML
- IronBackpacks
- ironchest
- jei
- journeymap
- KleeSlabs
- LongFallBoots 
- LunatriusCore
- Mantle
- mcjtylib
- MCMultiPart
- Mercurius
- MobGrindingUtils
- ModTweaker2
- Morpheus
- MouseTweaks
- mpbasic
- mputils
- MTLib
- natura
- NotEnoughItems
- OpenComputers
- Psi
- QuantumStorage
- rangedpumps
- RebornCore
- refinedstorage
- ResourceLoader
- rftools
- rftoolsctrl
- rftoolsdim
- roots
- ShadowMC
- shetiphiancore
- SimplyJetpacks2
- Snad
- SolarFluxReborn
- SonarCore
- StevesCarts
- StorageDrawers
- SuperCircuitMaker
- TConstruct
- TinkerToolLeveling
- torchmaster
- Translocators
- UniDict
- valkyrielib
- WanionLib
- zerocore****

**Comment by codeHusky** [comment]
After some further investigation it seems it might be a config issue.

**Comment by codeHusky** [comment]
Appears to not be a config issue.

**Comment by codeHusky** [comment]
#Updated list of possible contenders.
- ActuallyAdditions
- AppleSkin
- AutoRegLib
- bdlib
- BedBugs
- BetterBuildersWands
- BetterThanBunnies
- BloodMagic
- Botania r1.9
- BrandonsCore
- Ceramics
- Chameleon
- ChestTransporter
- Chisel
- chiselsandbits
- Clipboard
- CodeChickenCore
- CodeChickenLib
- compatlayer
- Controlling
- CookingForBlockheads
- CustomMainMenu
- DarkUtilities
- Decocraft
- Draconic
- DrawersBits
- ElevatorMod[V.1.3.0][MC.1.10.2].jar
- EnderCore
- EnderIO
- EnderStorage
- EngineersWorkshop
- environmentaltech
- etlunar
- extrautils2
- ExtremeReactors
- flatcoloredblocks
- FluxNetworks
- foamfix
- Forgelin
- FTBLib
- FTBUtilities
- Funnels
- GraveStone Mod 1.5.12.jar
- Guide
- HammerCore
- hopperducts
- ImmersiveEngineering
- InGameInfoXML
- IronBackpacks
- ironchest
- jei
- journeymap
- KleeSlabs
- LongFallBoots
- LunatriusCore
- Mantle
- mcjtylib
- MCMultiPart
- Mercurius
- MobGrindingUtils
- ModTweaker2
- Morpheus
- MouseTweaks
- mpbasic
- mputils
- MTLib
- natura
- NotEnoughItems
- OpenComputers
- Psi
- QuantumStorage
- rangedpumps
- RebornCore
- refinedstorage
- ResourceLoader
- rftools
- rftoolsctrl
- rftoolsdim
- roots
- ShadowMC
- shetiphiancore
- SimplyJetpacks2
- Snad
- SolarFluxReborn
- SonarCore
- StevesCarts
- StorageDrawers
- SuperCircuitMaker
- TConstruct
- TinkerToolLeveling
- torchmaster
- Translocators
- UniDict
- valkyrielib
- WanionLib
- zerocore

**Comment by codeHusky** [comment]
Anyone that is still experiencing this issue, please contact me on the support discord. This issue is closing due to the lack of help from those affected in replicating the issue.

**Comment by codeHusky** [comment]
Evidence shows that somehow it's something im doing in the code. How peculiar.

**Comment by codeHusky** [comment]
Ends up that keys were still saving to the config after the DB update. that breaks some stuff lol
