### ISSUE TITLE
GUI-Based crate creation

### ISSUE THREAD

**Issue by Eufranio** [codeHusky/HuskyCrates-Sponge#50]
Dealing with a lot of config is a mess (altrough I know how they work). I'd suggest you adding a **/crate create <crate>** command that would open a GUI for the player (admin), and he can put items there. After closing it, every slot would be serialized as an item of the **<crate>** crate, and it's config would be automatically saved. Any other values like weight, lang and etc would be the defaults one when saving, so the admin can change it directly in the config later.

Also, if the above is implemented, **/crate edit <crate>** could be useful to edit the crate items. It would open the chest GUI again for you, showing the items that are currently in that crate, so you can remove/add/edit them.

**Comment by codeHusky** [comment]
See HuskyConfigurator for more info. <3

**Comment by codeHusky** [comment]
closing since this is technically just HuskyConfigurator
