### ISSUE TITLE
Item specific lang data

### ISSUE THREAD

**Issue by caunt** [codeHusky/HuskyCrates-Sponge#51]
Hello, latest commit is good, but needs a little change.

 I suggest to use thisData.[SOMETHING] in CrateView.java only when vc.getLangData().[SOMETHING].isVirtual()

ex:
if (vc.getLangData().[SOMETHING].isVirtual())
{
// sendMessageToPlayerFromthisData();
}
else
{
// sendMessageToPlayerFromvcGetLangData();
}

**Comment by codeHusky** [comment]
I'm not even sure what your trying to convey here. Once again, closing until you communicate yourself better.
