### ISSUE TITLE
Holograms

### ISSUE THREAD

**Issue by caunt** [codeHusky/HuskyCrates-Sponge#52]
For now HuskyCrates do not remove previous ArmorStands at server startup. This is because ArmorStand interface not support setCreator() method. You can see [there](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/entity/living/ArmorStand.java) what u can use in ArmorStand object

**Comment by caunt** [comment]
del

**Comment by codeHusky** [comment]
Unless your using a ridiculously old API version, this isn't an issue. Unless you prove me otherwise, marking invalid.
