### ISSUE TITLE
Holograms removed on server start

### ISSUE THREAD

**Issue by SubtypeZero** [codeHusky/HuskyCrates-Sponge#57]
Clearing armor stands causes a problem for users of the [Holograms](https://github.com/randombyte-developer/holograms) plugin. By doing this, all holographic displays are removed on restart and the developer of the other plugin has not implemented the saving of holograms to a config file, which means that I'd either have to remove HuskyCrates or go without Holograms until one of the two plugins are updated to fix this issue. I have also reported this issue on their Github.

https://github.com/codeHusky/HuskyCrates-Sponge/blob/511bb7b4001d277e883569de0c5c02529ca21b18/src/main/java/com/codehusky/huskycrates/HuskyCrates.java#L220

**Comment by codeHusky** [comment]
All holograms are **not** removed on startup.

Unless someone's PR or something broke the removal mechanism, it only removes specially marked holograms. This issue was fixed ages ago.

**Comment by codeHusky** [comment]
I haven't been able to reproduce this during testing so I'm closing the issue.
