### ISSUE TITLE
Separate files per crate

### ISSUE THREAD

**Issue by Whazaaaaa** [codeHusky/HuskyCrates-Sponge#58]
I'd love to be able to make seperate files for each crate I make. After the 10th crate having it all in 1 files is very annoying to find what you need and edit what you need. This will also make it much easier when copying crates to different servers when for example you only want 8/10 of the crates you've created, instead of having to find the crates and remove them.

Or perhaps there is already a proper way to do this. If so how? ^^

Thanks

- Whazaaaaa

**Comment by codeHusky** [comment]
Separate files per crate will not be a feature for main crate development. This practice is kinda excessive and makes loading WAY harder than it needs to be. I don't see this becoming a thing for a while yet, but it'll happen eventually.

**Comment by randombyte-developer** [comment]
You can work around it using the built in [`inlcude`](https://github.com/lightbend/config/blob/master/HOCON.md#includes) of HOCON.

**Comment by codeHusky** [comment]
Not going to do this. Use `include` as mentioned by randombyte.
