### ISSUE TITLE
Add auto-completion of commands

### ISSUE THREAD

**Issue by ziceptor** [codeHusky/HuskyCrates-Sponge#6]
^ -- tab key

forge-1.11.2-13.20.0.2201-universal.jar
spongeforge-1.11.2-2201-6.0.0-BETA-2040.jar
HuskyCrates.v0.8.2.API6.x.jar

**Comment by KasperFranz** [comment]
This is in my PR #25

**Comment by codeHusky** [comment]
Wonderful, we might see this feature sooner than I expected.
