### ISSUE TITLE
3 more configuration fields

### ISSUE THREAD

**Issue by evernife** [codeHusky/HuskyCrates-Sponge#65]
A field to place a message that will be shown to the player when he receives a reward.
And a field to show everyone a message when a player receive a specific reward.

For now i am using commands :S

![image](https://user-images.githubusercontent.com/11357801/33403642-4d0e48a0-d548-11e7-8aeb-fbd88bbfddf1.png)

And,  a field to change the amout of items to be shown on the gui when opening a crate. (For command rewards in case)

**Comment by LoneWolffy** [comment]
> Use the Lang configuration to have messages display when receiving a reward
http://huskycrates.readthedocs.io/en/1.7.x/config_write.html#lang-options
You can also checks example using it here
http://huskycrates.readthedocs.io/en/1.7.x/examples.html

To change the amount of items in the crate gui you would up the "count" section to display a higher number of numbers in the stack
If you meant the amount of different items displayed, you can up the amount of maximum clicks along with additional mix/min 's to the number to be unique per open found here
http://huskycrates.readthedocs.io/en/1.7.x/config_write.html#spinner-options-optional
and as per above, you can find the spinner options in use in some examples here
http://huskycrates.readthedocs.io/en/1.7.x/examples.html

Remember the Wiki is your friend!
http://huskycrates.readthedocs.io/en/1.7.x/index.html

**Comment by codeHusky** [comment]
I won't be adding specific printout entries in this plugin for a while. I'll keep this in mind though.
What LoneWolffy said was true, though.

**Comment by evernife** [comment]
@LoneWolffy i love the wiki, ty

But.. as i just said:

> And, a field to change the amout of items to be shown on the gui when opening a crate. (For command rewards in case)

In the wiki we have: 

![image](https://user-images.githubusercontent.com/11357801/33404074-19c93aa2-d54a-11e7-9953-47dbd43bbd94.png)

Shall i use the `overrideCount `?

--------------
And the lang (at least in the exemple there) is for an entire crate type, not for an Item of a crate.

![image](https://user-images.githubusercontent.com/11357801/33404166-6cee9be6-d54a-11e7-8ef1-218ff86121e0.png)

@codeHusky Thank you ^^

**Comment by codeHusky** [comment]
@evernife Sorry, the docs are wrong on that. No idea why it even says that. You're free to use as much of an item as youd like for displaying it

**Comment by codeHusky** [comment]
Suggestions in here will be moved to another place soon
