### ISSUE TITLE
A way to preview a chest

### ISSUE THREAD

**Issue by evernife** [codeHusky/HuskyCrates-Sponge#66]
Event from a command or by hitting a chest 🗡 

Sorry, my bad :V  i saw it now

**Comment by LoneWolffy** [comment]
There is an option for that found here
http://huskycrates.readthedocs.io/en/1.7.x/config_write.html#crate-options
"showRewardsOnLeft=true" 
I linked you the wiki earlier, please don't use github for issues - rather use the discord or the wiki and read first!

**Comment by evernife** [comment]
yep, i am sorry for that
