### ISSUE TITLE
NamedCause Error on Startup

### ISSUE THREAD

**Issue by merjilin** [codeHusky/HuskyCrates-Sponge#67]
Hey there, CodeHusky! Upon installing this plugin on API 7, I've bumped into an error. I'm not entirely sure where this error is coming from, even after looking through the commits on the sponge repo, so I'm left clueless, I can't find anything regarding a NamedCause class.

Here is the error which is displayed in console: https://gist.github.com/merjilin/2f3d5a38cb2ce7f1b0f9326cd5d22974

Environment:
- spongeforge-1.12.2-2555-7.0.0-BETA-2758.jar 
- HuskyCrates-1.7.2.jar 

I hope this isn't too much hassle, as the error is also given for HuskyGUI. If needed, I will open an issue on that repo as well :)

I did think this was an error due to us using SpongeBootstrap. But it seems the error is still prevalent after removing it. 

Kind regards, merjilin

**Comment by codeHusky** [comment]
please use the version posted for api 7
it's necessary for you to use the plugin.
Please carefully read the release info next time.

**Comment by merjilin** [comment]
Oh bugger! Terribly sorry about that. 

I wait straight to the ore page rather than checking on the plugin release page :)
