### ISSUE TITLE
Flickering prize in the finals

### ISSUE THREAD

**Issue by ziceptor** [codeHusky/HuskyCrates-Sponge#7]
Flickering prize in the finals in the central cell. Unpleasant effect.

forge-1.11.2-13.20.0.2201-universal.jar
spongeforge-1.11.2-2201-6.0.0-BETA-2040.jar
HuskyCrates.v0.8.2.API6.x.jar

**Comment by ziceptor** [comment]
[Picture](https://cloud.mail.ru/public/L3jw/pZ6HuTBJu)

**Comment by codeHusky** [comment]
Sponge bug, can't fix right now
