### ISSUE TITLE
Null pointer with husky ui 4.1 and pre 2

### ISSUE THREAD

**Issue by unstablecraft** [codeHusky/HuskyCrates-Sponge#75]
for some reason huskey crates stopped working this morning giving me this error 

https://gist.github.com/unstablecraft/0cd26686ef97fdf40ccda6c6ea5ab1af

hope you can solve it  
if you need more info @me

**Comment by unstablecraft** [comment]
https://gist.github.com/unstablecraft/ede68de56e948cc5eec84a7305ec3cbf

its something in your DB that is buggy

**Comment by codeHusky** [comment]
@unstablecraft use pre 2.1
