### ISSUE TITLE
Invalid item name returned for reward

### ISSUE THREAD

**Issue by ziceptor** [codeHusky/HuskyCrates-Sponge#8]
Config default. Receive a prize of diamonds. Chat message: You won a dirt from a Crate Command!

forge-1.11.2-13.20.0.2201-universal.jar
spongeforge-1.11.2-2201-6.0.0-BETA-2040.jar
HuskyCrates.v0.8.2.API6.x.jar

**Comment by ziceptor** [comment]
[https://cloud.mail.ru/public/CZ1V/Yti6VjsaV](https://cloud.mail.ru/public/CZ1V/Yti6VjsaV)

**Comment by codeHusky** [comment]
I can't reproduce this. I'll need like, more information than what you're giving me

**Comment by codeHusky** [comment]
Like your config or something. This seems awfully like a config issues since it makes no sense that this would happen.

**Comment by ziceptor** [comment]
[huskycrates.conf](http://pastebin.com/ikH4Uikz)
[video](https://cloud.mail.ru/public/84ny/yhww67tmK)

**Comment by ziceptor** [comment]
Always given diamonds. This may be related https://github.com/codeHusky/HuskyCrates-Sponge/issues/10

**Comment by codeHusky** [comment]
Going to look into this.
