### ISSUE TITLE
Crates not working right

### ISSUE THREAD

**Issue by Alex802c** [codeHusky/HuskyCrates-Sponge#86]
My crates are not working right. I have used the HuskyConfigurator and the converter. One of my crates work. But it says that the others are not valid crates. 

Here is a file of my config. 

[LKMw265F.txt](https://github.com/codeHusky/HuskyCrates-Sponge/files/2729696/LKMw265F.txt)

**Comment by codeHusky** [comment]
Go to the support discord for help with configs.
