### ISSUE TITLE
HuskyCrates Double Rewards 

### ISSUE THREAD

**Issue by KhaozFrost** [codeHusky/HuskyCrates-Sponge#88]
https://gist.github.com/KhaozFrost/bd73f37097796435b6849b4b8219401e

HuskyCrates-v2.0.0-PRE9H2-API7.jar
HuskyUI-v0.6.0-PRE3-API7.jar
spongeforge-1.12.2-2768-7.1.6-RC3625.jar

test crate setup
https://pastebin.com/6B8k1MG8
http://prntscr.com/mwmhm3

**Comment by KhaozFrost** [comment]
seems to happen ever since this update.
https://github.com/SpongePowered/SpongeCommon/issues/2208

If you allow the crate to play through the animation to the end and not force close it; it'll dupe, but if you instantly close the gui as soon as its opened it'll only issue the rewards 1 time.

I can change the crates all to instant and it doesn't dupe. so its an issue with the gui changes most certainly.

**Comment by codeHusky** [comment]
Will look tomorrow since it's late rn

Thanks for the spongecommon info, it'll help

**Comment by codeHusky** [comment]
Will note that this is only an issue on more recent Sponge versions

**Comment by krisjenner** [comment]
I'm having a similar issue. 

Having 2 keys and force closing the GUI the first time but letting it run to the end the second time will issue 2 of the same rewards.
