### ISSUE TITLE
Interrupt only ran once crate has finished

### ISSUE THREAD

**Issue by julianubico** [codeHusky/HuskyCrates-Sponge#90]
Interrupt only seems to run once the crate has finished, not when I close out of the menu with `ESC` or `E`. I've also added some code to the interrupt code and it shows that it is only doing it after the crate has "finished".
Using: 
- SpongeForge 7.1.6-RC3616
- HuskyCrates-2.0.0-PRE9-H2
- HuskyUI-v0.6.0-PRE2-H3.jar
[**Video Example**](https://github.com/codeHusky/HuskyCrates-Sponge/files/3145077/Bug.mov.zip)

![Image](https://i.gyazo.com/0c76284cef5c9bd2ffd93ae0ea49e5d6.png)

**Comment by codeHusky** [comment]
Some versions of sponge don't play nicely with HuskyCrates. It's best to stay up-to-date.
