### ISSUE TITLE
Crates are not valid

### ISSUE THREAD

**Issue by Switchmyscore** [codeHusky/HuskyCrates-Sponge#95]
Ok, so I used the crate generator and then used the converter to get the crate.conf. Though every time i try to spawn the crate is says it doesn't exist.

Error: https://gyazo.com/333c3a5cdb2883ec4e0a98315708132b

Config: 
Elite {
    cooldownSeconds=10
    effects {
        idle {
            particles=[
                {
                    animationPreset=orbit
                    color=[
                        1,
                        122,
                        134
                    ]
                    type="minecraft:redstone_dust"
                },
                {
                    animationPreset=orbit
                    color=[
                        1,
                        122,
                        134
                    ]
                    type="minecraft:redstone_dust"
                }
            ]
        }
    }
    free=true
    hologram {
        lines=[
            "Elite Crate"
        ]
    }
    name="EliteCrate"
    slots=[
        {
            chance=1.0
            displayItem {
                count=1
                damage=339
                id="339"
                name="Random Shiny"
            }
            rewards=[
                {
                    data="pokegive %p random shiny"
                    type=servercommand
                },
                {
                    data="You won %a %R&r from a %C&r!"
                    type=usermessage
                }
            ]
        },
        {
            chance=5.0
            displayItem {
                count=1
                damage=339
                id="339"
                name="Random Pokemon"
            }
            rewards=[
                {
                    data="pokegive %p random"
                    type=servercommand
                },
                {
                    data="You won %a %R&r from a %C&r!"
                    type=usermessage
                }
            ]
        },
        {
            chance=10.0
            displayItem {
                count=1
                damage=339
                id="339"
                name="Random Money"
            }
            rewards=[
                {
                    data="/adminpay %p 500"
                    type=servercommand
                },
                {
                    data="You won %a %R&r from a %C&r!"
                    type=usermessage
                }
            ]
        }
    ]
    useLocalKey=true
    viewType=spinner
}

**Comment by codeHusky** [comment]
Please go to the support discord for assistance.
