### ISSUE TITLE
*VERY* serious duplication glitch with Quark (CLIENTSIDE)

### ISSUE THREAD

**Issue by ghost** [codeHusky/HuskyCrates-Sponge#98]
Hey there,
First off; awesome work on the Plugin! It's incredible!

Anyway, i'm reporting a very serious bug with HuskyCrates x Quark.
Usually, you cannot take out items from the ChestGUI, with Quark, it adds icons to the LEFT side of the ChestGUI (see attached)
![image](https://user-images.githubusercontent.com/44342726/77805343-8ef50f00-7079-11ea-9584-44ed018bb716.png)

Pressing the "Extract" button (see attached) results in literally taking out every single item from the GUI.
![image](https://user-images.githubusercontent.com/44342726/77805381-a7652980-7079-11ea-9478-64e1759c3583.png)
![image](https://user-images.githubusercontent.com/44342726/77805388-ab914700-7079-11ea-8e24-d06f27a70463.png)
![image](https://user-images.githubusercontent.com/44342726/77805392-acc27400-7079-11ea-8733-a74b0167ba26.png)

These screenshots show before, during and after the "Extract" button is pressed.
![image](https://user-images.githubusercontent.com/44342726/77805418-bc41bd00-7079-11ea-92b4-9bd3d1e1d9fd.png)

This works in survival mode also ^
![image](https://user-images.githubusercontent.com/44342726/77805440-c6fc5200-7079-11ea-8c6c-356f764b23f0.png)

So, why is this very serious?
HuskyCrates provides crates to servers, whether they use them as monetisation or not, it's up to the developer/owner. This is very serious because obviously these items are meant to be earned/spun for. Not just exported out as if you get every single item in the spin.

**Comment by ghost** [comment]
^ Quark is installed on both ends.

**Comment by ShadierChi** [comment]
Are you sure this is Inventory Tweaks? I use Inventory Tweaks and these buttons are not there.

**Comment by ghost** [comment]
The mod is called Quark, sorry, I apologise for this.

**Comment by codeHusky** [comment]
Uninstall the mod server side, there's nothing I can do to fix this from my end. Or ask the developer to make it play better with Sponge.
