### ISSUE TITLE
crates config file syntax sugguestion 

### ISSUE THREAD

**Issue by nicholasrobertm** [codeHusky/HuskyCrates-Sponge#99]
Hey there! 

In the crates config the formatting seems to be following some custom format, could these be changed to yaml / json potentially? 

I wrote a small ruby script to generate config based on the list of items which I've now got working but ran into some issues.

Here is an example of what I got that was working:
`{
	  chance=3.0
	  displayItem {
		  count=1
		  id="nuclearcraft:dominos"
		  lore=[
			"1 Dominos"
		  ]
		  name="Dominos"
	  }
	  rewards=[
          {
		      data="give %p nuclearcraft:dominos 1"
		      type=servercommand
	      }
          {
		      data="bc &a%p &6won a Domino's Special!"
		      type=servercommand
	      }
      ]
},`

However the same thing with just slightly different spacing / formatting:
`{
	  chance=3.0
	  displayItem {
		  count=1
		  id="nuclearcraft:dominos"
		  lore=[
			"1 Dominos"
		  ]
		  name="Dominos"
	  }
	  rewards=[{
		      data="give %p nuclearcraft:dominos 1"
		      type=servercommand
	      }{
		      data="bc &a%p &6won a Domino's Special!"
		      type=servercommand
              }
      ]
},`

Results in the item showing up in the husky crate, and the broadcast command running, but the give command not running. I think it'd be beneficial to make this config file follow a yaml / json format, either would be much more readable by both humans and machines

**Comment by nicholasrobertm** [comment]
Oops looks like github has messed with the formatting. here is a picture ,pay close attention to the difference in the 'rewards' array:
https://imgur.com/a/QBPRoBg

**Comment by codeHusky** [comment]
Hi.
We're using HOCON (Human-Optimized Config Object Notation), which is standard for all Sponge plugins.
https://github.com/lightbend/config/blob/master/HOCON.md
For additional plugin-specific info, see http://codehusky.com/huskycrates .
